/**
 * The pool of mystery places.
 *
 * Latitude drives every curve, so the numbers matter more than anything
 * else on this page. Facts stay short and checkable; anything that needed a
 * caveat is left out.
 */
export type Place = {
  /** Stable key for React lists and tests. */
  id: string;
  name: string;
  country: string;
  /** Degrees, positive north. City-centre or station coordinates, 2 decimals. */
  lat: number;
  fact: string;
};

export const PLACES: readonly Place[] = [
  {
    id: "longyearbyen",
    name: "Longyearbyen",
    country: "Svalbard, Norway",
    lat: 78.22,
    fact: "The northernmost town of any size on Earth; snowmobiles outnumber residents.",
  },
  {
    id: "tromso",
    name: "Tromsø",
    country: "Norway",
    lat: 69.65,
    fact: "Northern Norway's largest city and a classic base for aurora watching.",
  },
  {
    id: "rovaniemi",
    name: "Rovaniemi",
    country: "Finland",
    lat: 66.5,
    fact: "Marketed as Santa Claus's official hometown, right beside the Arctic Circle.",
  },
  {
    id: "fairbanks",
    name: "Fairbanks",
    country: "Alaska, USA",
    lat: 64.84,
    fact: "Interior Alaska's hub, sitting under the auroral oval.",
  },
  {
    id: "reykjavik",
    name: "Reykjavík",
    country: "Iceland",
    lat: 64.15,
    fact: "The northernmost capital of a sovereign state.",
  },
  {
    id: "anchorage",
    name: "Anchorage",
    country: "Alaska, USA",
    lat: 61.22,
    fact: "Alaska's largest city, between Cook Inlet and the Chugach mountains.",
  },
  {
    id: "helsinki",
    name: "Helsinki",
    country: "Finland",
    lat: 60.17,
    fact: "Finland's capital; in June the nights stay light from dusk to dawn.",
  },
  {
    id: "st-petersburg",
    name: "Saint Petersburg",
    country: "Russia",
    lat: 59.94,
    fact: "Famous for its White Nights, when the city never really goes dark.",
  },
  {
    id: "stockholm",
    name: "Stockholm",
    country: "Sweden",
    lat: 59.33,
    fact: "Sweden's capital, built across fourteen islands.",
  },
  {
    id: "edinburgh",
    name: "Edinburgh",
    country: "Scotland",
    lat: 55.95,
    fact: "Scotland's capital, with an extinct volcano standing in the middle of it.",
  },
  {
    id: "moscow",
    name: "Moscow",
    country: "Russia",
    lat: 55.75,
    fact: "The largest city in Europe by population.",
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    lat: 55.68,
    fact: "Denmark's capital, where about half of all trips to work or school are by bike.",
  },
  {
    id: "berlin",
    name: "Berlin",
    country: "Germany",
    lat: 52.52,
    fact: "Germany's capital; its area is roughly nine times that of Paris.",
  },
  {
    id: "london",
    name: "London",
    country: "United Kingdom",
    lat: 51.51,
    fact: "Shares its latitude with Dresden and with Calgary.",
  },
  {
    id: "dresden",
    name: "Dresden",
    country: "Germany",
    lat: 51.05,
    fact: "Home base of the fox who built this game, on the Elbe in Saxony.",
  },
  {
    id: "calgary",
    name: "Calgary",
    country: "Canada",
    lat: 51.05,
    fact: "Canada's oil-industry headquarters, in the foothills of the Rockies.",
  },
  {
    id: "vancouver",
    name: "Vancouver",
    country: "Canada",
    lat: 49.28,
    fact: "Canada's Pacific gateway, squeezed between the Coast Mountains and the sea.",
  },
  {
    id: "vienna",
    name: "Vienna",
    country: "Austria",
    lat: 48.21,
    fact: "Austria's capital and home of the Spanish Riding School.",
  },
  {
    id: "seattle",
    name: "Seattle",
    country: "Washington, USA",
    lat: 47.61,
    fact: "Pacific Northwest port city, with Mount Rainier on the skyline.",
  },
  {
    id: "sapporo",
    name: "Sapporo",
    country: "Japan",
    lat: 43.06,
    fact: "Host of the 1972 Winter Olympics and of a famous snow festival.",
  },
  {
    id: "rome",
    name: "Rome",
    country: "Italy",
    lat: 41.9,
    fact: "Italy's capital, wrapped around Vatican City.",
  },
  {
    id: "istanbul",
    name: "Istanbul",
    country: "Türkiye",
    lat: 41.01,
    fact: "The one big city on two continents, split by the Bosphorus.",
  },
  {
    id: "new-york",
    name: "New York City",
    country: "USA",
    lat: 40.71,
    fact: "The most populous city in the United States.",
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    lat: 38.72,
    fact: "Mainland Europe's westernmost capital, at the mouth of the Tagus.",
  },
  {
    id: "tokyo",
    name: "Tokyo",
    country: "Japan",
    lat: 35.68,
    fact: "The world's largest metropolitan area, around 37 million people.",
  },
  {
    id: "buenos-aires",
    name: "Buenos Aires",
    country: "Argentina",
    lat: -34.6,
    fact: "Argentina's capital, on the Río de la Plata.",
  },
  {
    id: "sydney",
    name: "Sydney",
    country: "Australia",
    lat: -33.87,
    fact: "Australia's biggest city; the Opera House sits on the harbour.",
  },
  {
    id: "cape-town",
    name: "Cape Town",
    country: "South Africa",
    lat: -33.92,
    fact: "South Africa's legislative capital, under Table Mountain.",
  },
  {
    id: "santiago",
    name: "Santiago",
    country: "Chile",
    lat: -33.45,
    fact: "Chile's capital, with the Andes rising right behind it.",
  },
  {
    id: "perth",
    name: "Perth",
    country: "Australia",
    lat: -31.95,
    fact: "Australia's most isolated big city, on the Indian Ocean.",
  },
  {
    id: "cairo",
    name: "Cairo",
    country: "Egypt",
    lat: 30.04,
    fact: "Africa's largest city, spread along the Nile.",
  },
  {
    id: "taipei",
    name: "Taipei",
    country: "Taiwan",
    lat: 25.03,
    fact: "Taiwan's capital, in a basin ringed by mountains.",
  },
  {
    id: "havana",
    name: "Havana",
    country: "Cuba",
    lat: 23.11,
    fact: "Inside the tropics, just south of the Tropic of Cancer.",
  },
  {
    id: "honolulu",
    name: "Honolulu",
    country: "Hawaii, USA",
    lat: 21.31,
    fact: "Hawaii's capital, on the island of Oahu.",
  },
  {
    id: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    lat: 19.43,
    fact: "Some 2,240 m above sea level, one of the highest large cities on Earth.",
  },
  {
    id: "mumbai",
    name: "Mumbai",
    country: "India",
    lat: 19.08,
    fact: "India's financial capital, on the Arabian Sea.",
  },
  {
    id: "bangkok",
    name: "Bangkok",
    country: "Thailand",
    lat: 13.76,
    fact: "Thailand's capital, on the Chao Phraya river.",
  },
  {
    id: "lima",
    name: "Lima",
    country: "Peru",
    lat: -12.05,
    fact: "Peru's capital, in a coastal desert that almost never rains.",
  },
  {
    id: "darwin",
    name: "Darwin",
    country: "Australia",
    lat: -12.46,
    fact: "Australia's northernmost capital, well inside the tropics.",
  },
  {
    id: "colombo",
    name: "Colombo",
    country: "Sri Lanka",
    lat: 6.93,
    fact: "Sri Lanka's biggest city, on the island's west coast.",
  },
  {
    id: "bogota",
    name: "Bogotá",
    country: "Colombia",
    lat: 4.71,
    fact: "Colombia's capital, 2,640 m up in the Andes.",
  },
  {
    id: "singapore",
    name: "Singapore",
    country: "Singapore",
    lat: 1.35,
    fact: "A city-state just north of the equator.",
  },
  {
    id: "quito",
    name: "Quito",
    country: "Ecuador",
    lat: -0.18,
    fact: "The capital city closest to the equator.",
  },
  {
    id: "pontianak",
    name: "Pontianak",
    country: "Indonesia",
    lat: -0.02,
    fact: "A city on Borneo that sits almost exactly on the equator.",
  },
  {
    id: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    lat: -1.29,
    fact: "Kenya's capital, 1,795 m up at the edge of the Rift Valley.",
  },
  {
    id: "dar-es-salaam",
    name: "Dar es Salaam",
    country: "Tanzania",
    lat: -6.79,
    fact: "Tanzania's biggest city, on the Indian Ocean.",
  },
  {
    id: "rio",
    name: "Rio de Janeiro",
    country: "Brazil",
    lat: -22.91,
    fact: "Just south of the Tropic of Capricorn, between mountains and beaches.",
  },
  {
    id: "wellington",
    name: "Wellington",
    country: "New Zealand",
    lat: -41.29,
    fact: "The southernmost capital of a sovereign state.",
  },
  {
    id: "hobart",
    name: "Hobart",
    country: "Tasmania, Australia",
    lat: -42.88,
    fact: "Tasmania's capital, at the foot of Mount Wellington.",
  },
  {
    id: "christchurch",
    name: "Christchurch",
    country: "New Zealand",
    lat: -43.53,
    fact: "The South Island's biggest city, rebuilt after the 2011 earthquake.",
  },
  {
    id: "invercargill",
    name: "Invercargill",
    country: "New Zealand",
    lat: -46.41,
    fact: "New Zealand's southernmost city.",
  },
  {
    id: "kerguelen",
    name: "Port-aux-Français",
    country: "Kerguelen Islands, France",
    lat: -49.35,
    fact: "A French research base on the sub-Antarctic 'Islands of Desolation'.",
  },
  {
    id: "punta-arenas",
    name: "Punta Arenas",
    country: "Chile",
    lat: -53.16,
    fact: "A Chilean port on the Strait of Magellan.",
  },
  {
    id: "ushuaia",
    name: "Ushuaia",
    country: "Argentina",
    lat: -54.8,
    fact: "Often called the world's southernmost city, on Tierra del Fuego.",
  },
];
